// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/wangyonghong/Documents/data_tools/loonshots-web-lite/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import ProjectOutlined from '/Users/wangyonghong/Documents/data_tools/loonshots-web-lite/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/ProjectOutlined';
import FileOutlined from '/Users/wangyonghong/Documents/data_tools/loonshots-web-lite/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/FileOutlined';
import ApartmentOutlined from '/Users/wangyonghong/Documents/data_tools/loonshots-web-lite/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/ApartmentOutlined';
import FolderOutlined from '/Users/wangyonghong/Documents/data_tools/loonshots-web-lite/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/FolderOutlined';
import TeamOutlined from '/Users/wangyonghong/Documents/data_tools/loonshots-web-lite/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/TeamOutlined';
export default { DashboardOutlined, ProjectOutlined, FileOutlined, ApartmentOutlined, FolderOutlined, TeamOutlined };
