// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { connect, useDispatch, useStore, useSelector } from '/Users/wangyonghong/Documents/data_tools/loonshots-web-lite/node_modules/.pnpm/@umijs+plugins@4.4.10_@babel+core@7.27.1_@types+react-dom@17.0.26_@types+react@18.3.21_antd@4_riuuwbozfkj64mw47gwyeierzu/node_modules/@umijs/plugins/libs/dva.tsx';
export { getDvaApp } from './dva';
