apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-01-22T07:05:17Z"
  generation: 1
  labels:
    app: annotation-tools
  name: annotation-tools
  namespace: loonshots-dev
  resourceVersion: "25197108"
  selfLink: /apis/extensions/v1beta1/namespaces/loonshots-dev/deployments/annotation-tools
  uid: 8ba28745-3ce5-11ea-a3f7-00163e090e62
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: annotation-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: annotation-tools
    spec:
      containers:
      - image: registry-intl-vpc.cn-zhangjiakou.aliyuncs.com/loonshots/annotation-tools:latest
        imagePullPolicy: Always
        name: annotation-tools
        ports:
        - containerPort: 3000
          name: port
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-jdk
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-22T07:05:20Z"
    lastUpdateTime: "2020-01-22T07:05:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-22T07:05:17Z"
    lastUpdateTime: "2020-01-22T07:05:20Z"
    message: ReplicaSet "annotation-tools-65848d6678" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
