// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/models/login';
import model_2 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/models/user';
import model_3 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/bpo/models/bpoJobDetail';
import model_4 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/bpo/models/bpoList';
import model_5 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/project/models/dataCenter';
import model_6 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/project/models/project';
import model_7 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/project/models/projectAccess';
import model_8 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/project/models/uploadProgress';
import model_9 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/project/workflow/models/flowCreation';
import model_10 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/project/workflow/models/flowDetail';
import model_11 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/project/workflow/models/jobDetail';
import model_12 from '/Users/qzheng/Documents/webroot/loonshots-web-lite/src/pages/worker-job/models/workerJob';

export const models = {
model_1: { namespace: 'login', model: model_1 },
model_2: { namespace: 'user', model: model_2 },
model_3: { namespace: 'bpo.bpoJobDetail', model: model_3 },
model_4: { namespace: 'bpo.bpoList', model: model_4 },
model_5: { namespace: 'project.dataCenter', model: model_5 },
model_6: { namespace: 'project.project', model: model_6 },
model_7: { namespace: 'project.projectAccess', model: model_7 },
model_8: { namespace: 'project.uploadProgress', model: model_8 },
model_9: { namespace: 'project.workflow.flowCreation', model: model_9 },
model_10: { namespace: 'project.workflow.flowDetail', model: model_10 },
model_11: { namespace: 'project.workflow.jobDetail', model: model_11 },
model_12: { namespace: 'worker-job.workerJob', model: model_12 },
} as const
